babel.config.js
components/TokenSelector/TokenSelectorModal.tsx

- **remove the pluging that is causing android builds to fail**
- **use Text instead of span**

fix launch error on android

---

app/(protected)/(tabs)/card/bridge_terms_of_service.tsx
app/(protected)/(tabs)/card/index.tsx
app/(protected)/(tabs)/card/kyc.tsx
app/(protected)/card/activate.tsx
constants/path.ts
hooks/useCustomer.ts
hooks/useNav.ts
lib/api.ts
lib/types.ts

- **create components to show terms of service and KYC pages in iframe**
- **add functions to create/get KYC links**
- **add the Card menu item**
- **push the activate route on button click**

implement kyc flow for card

---

app/(protected)/(tabs)/deposit.tsx
components/Withdraw/index.tsx
hooks/useBridgeToMainnet.ts
hooks/useDeposit.ts
hooks/useWithdraw.ts

- Updated deposit and withdraw hooks to return transaction receipts.
- Integrated success and error Toast notifications for deposit and bridge actions, linking to LayerZero Scan for transaction details.
- Improved error handling in deposit and withdraw processes.

Enhance deposit and withdraw flows with transaction feedback

---

app/(protected)/(tabs)/dashboard.tsx
hooks/useUser.ts
hooks/useVault.ts

- Added checkBalance function to useUser hook for user balance verification.
- Implemented useEffect in Dashboard to call checkBalance when user changes.
- Enhanced error handling in useUser for various async operations.
- Cleaned up imports in dashboard.tsx and useUser.ts for better organization.

Refactor Dashboard and useUser hook to include balance checking and error handling

---

hooks/useUser.ts

- Memoize all callback functions with useCallback to prevent unnecessary re-renders
- Extract constants for magic strings (addresses, versions, error messages)
- Improve error handling with centralized ERROR_MESSAGES object
- Refactor checkBalance to use try-catch-finally pattern
- Create reusable createDeadOwnerAccount utility function
- Optimize useCallback dependencies for better performance
- Add proper TypeScript typing for dummyUser object
- Simplify async/await patterns for better readability
This improves component performance by preventing function recreation on every render and enhances code maintainability with better organization and consistent patterns.

refactor(useUser): apply React best practices for performance and maintainability

---

hooks/useUser.ts
metro.config.js
package-lock.json
package.json

- Added a custom resolver in metro.config.js to block browser-specific modules for native platforms.
- Updated @turnkey/sdk-browser to version 5.3.3 and axios to version 1.11.0.
- Updated form-data dependency to version 4.0.4.
- Removed @hpke/core from package.json and package-lock.json.

[UPDATE]: Enhance platform-specific module resolution in metro.config.js and update dependencies

---

app/(protected)/(tabs)/index.tsx

Refactored the loading state checks in the Dashboard component to use isBalanceLoading instead of balanceLoadOnce for better clarity. This change ensures that the loading indicators accurately reflect the current state of data fetching. Additionally, restructured imports for improved organization.

fix: Update loading state checks in Dashboard component

---

components/Dashboard/DashboardMobile.tsx
components/Wallet/CoinsMobile.tsx

Changed the rendering logic to display CoinsMobile only when the balance is not zero, improving the UI flow for users with no funds.

Update DashboardMobile to conditionally render CoinsMobile based on balance

---

components/DepositOption/DepositOptions.web.tsx

- Introduced 'isComingSoon' property to the Bank Deposit option, utilizing the 'isProduction' flag to conditionally render the feature.
- Updated DepositOptions component to reflect this change, enhancing user experience by indicating upcoming features.

feat: Add 'isComingSoon' flag to Bank Deposit option based on production environment

---

app/(protected)/(tabs)/kyc.tsx
app/(protected)/(tabs)/user-kyc-info.tsx
components/BankTransfer/payment/PaymentMethodList.tsx
lib/utils/kyc/index.ts

- Updated KYC components to eliminate the redirectUri parameter from the startKycFlow function.
- Adjusted related components (Kyc, UserKycInfo, PaymentMethodList) to reflect this change, simplifying the KYC link creation process.
- Enhanced code clarity by reducing unnecessary parameters and improving destructuring.

Refactor KYC flow to remove redirectUri parameter

---

app/(protected)/(tabs)/send.tsx

- Added useRouter for navigation functionality.
- Introduced a back button using ArrowLeft icon in the header.
- Updated header layout for improved user experience.

Update SendPage to include back navigation and header

---

components/BankTransfer/AmountCard.tsx
components/BankTransfer/AmountInput.tsx
components/BankTransfer/BankTransferModalContent.tsx
components/BankTransfer/KycModalContent.tsx
components/BankTransfer/enums.ts
components/BankTransfer/payment/PaymentMethodList.tsx
components/DepositOption/DepositOptionModal.tsx
components/DepositOption/DepositOptions.native.tsx
components/DepositOption/DepositOptions.web.tsx
constants/modals.ts
store/useDepositStore.ts

- Added logic to initiate KYC flow directly within the modal for bank transfer selection.
- Implemented redirect URI construction and endorsement retrieval based on selected payment method.
- Integrated state management updates to handle KYC data and modal visibility for both new and existing customers.
- Improved error handling for KYC link retrieval in modal mode.

Show-bank-deposit-in-modal

---

eas.json

- Included `ascAppId`, `appleTeamId`, `sku`, and `name` for iOS in the eas.json file to support app submission and identification.

feat: add iOS configuration to eas.json

---

components/DepositEmailModal/index.tsx

- Replaced inline styles with Tailwind CSS classes for input fields in DepositEmailModal.
- Improved consistency and responsiveness across web platforms.

style: update DepositEmailModal input styles for web compatibility

---

components/BankTransfer/payment/PaymentMethodList.tsx

- Added loading state to display an ActivityIndicator while fetching customer data.
- Implemented error handling with a Toast notification for bridge transfer failures.
- Improved user experience by providing feedback during data loading and error scenarios.

feat: enhance PaymentMethodList with loading state and error handling

---

app/register.tsx
hooks/useUser.ts

- Added Sentry error capturing for various failure points including token fetching, passkey creation, safe address updates, and signup/login processes.
- Updated dummy login button visibility to only show in development mode.

Enhance error handling with Sentry integration in useUser hook

---

hooks/swap/useSwapCallback.ts

- Updated useSwapCallback to handle errors in findBestCall gracefully, logging a warning and defaulting to the first call if an error occurs.
- Adjusted dependencies to include bestCall, ensuring proper reactivity in the hook.
These changes enhance the robustness of the swap functionality and improve user experience during transaction handling.

refactor: Improve error handling and best call selection in useSwapCallback

---

components/SendModal/index.tsx
components/Swap/SwapButton.tsx
components/Swap/SwapParams.tsx
components/Withdraw/index.tsx
hooks/swap/useVoltageRouter.ts
hooks/tokens/useAllTokens.ts
hooks/useBridgeToFuse.ts
hooks/useBridgeToMainnet.ts
hooks/useDeposit.ts
hooks/useDepositFromEOA.ts
hooks/useSend.ts
hooks/useUser.ts
hooks/useWithdraw.ts
lib/api.ts
lib/execute.ts
lib/pimlico.ts
store/usePointsStore.ts
store/useReferralStore.ts

- Integrated Sentry for error capturing and breadcrumb logging in SendModal, SwapButton, SwapParams, Withdraw, and multiple hooks including useBridgeToFuse, useDeposit, and useSend.
- Improved error handling by logging detailed context for transaction failures, user actions, and API errors, aiding in debugging and monitoring.
- Added Sentry breadcrumbs to track the flow of operations, enhancing observability for deposit, withdrawal, and bridging processes.
These changes significantly improve the error management capabilities and provide better insights into user interactions and transaction states.

feat: Enhance error tracking with Sentry integration across various components

---

hooks/useUser.ts

- Replaced direct call to pimlicoClient with bundlerClient for better encapsulation and clarity in the useUser hook.
- This change enhances the maintainability of the code by centralizing the client instantiation.

feat: Update paymaster to use bundlerClient in useUser hook

---

components/SendModal/index.tsx
hooks/swap/usePegswapCallback.ts
hooks/swap/useSwapCallback.ts
hooks/swap/useVoltageSwapCallback.ts
hooks/tokens/useNeedAllowance.ts
hooks/useApprove.ts

- Added Sentry integration for error logging in `useApprove` and `useSwapCallback`, enhancing debugging capabilities.
- Improved fallback handling in `useApprove` to ensure proper approval transactions are generated.
- Updated `useSwapCallback` to streamline approval checks and ensure correct transaction handling for token inputs.
- Enhanced `useNeedAllowance` to handle errors more gracefully and ensure accurate allowance checks.
- Added chainId to relevant hooks for better context in contract interactions.

fix: Refactor approval and swap logic in hooks

---

components/Activity/ActivityTransactions.tsx
components/DepositOption/DepositOptionModal.tsx
components/ResponsiveModal.tsx
components/Transaction/TransactionCredenza.tsx
components/Transaction/TransactionDrawer.tsx
components/Transaction/TransactionDropdown.tsx
components/Transaction/index.tsx
hooks/useAnalytics.ts
lib/api.ts
lib/types.ts
lib/types/bank-transfer.ts
store/useDepositStore.ts

- Added `type` and `onPress` props to `Transaction`, `TransactionDrawer`, and `TransactionDropdown` components for better interaction handling.
- Updated `TransactionCredenzaContent` to accept a `text` prop, allowing dynamic text based on transaction type.
- Modified press handlers in `TransactionDrawer` and `TransactionDropdown` to differentiate actions based on transaction type, specifically for bank transfers.
- Improved user experience by updating displayed text for bank transfers to "View details" instead of the default "View transaction".

Enhance Transaction components for bank transfer support

---

app/(protected)/(tabs)/savings.tsx
components/Savings/ExtraYield.tsx
components/Tooltip.tsx
components/ui/tooltip.tsx

- Introduced ExtraYield component to display additional APY information with tooltips.
- Updated TooltipPopover to accept new props for positioning and offset.
- Improved tooltip content for better user guidance in the ExtraYield component.
- Minor refactor in Savings component to include ExtraYield.

Add ExtraYield component and enhance TooltipPopover functionality

---

app/(protected)/(tabs)/card/deposit.tsx
app/(protected)/(tabs)/card/details.tsx
components/Card/CircularActionButton.tsx
constants/path.ts
lib/api.ts

- Introduced a new `DepositToCard` component that allows users to deposit stablecoins (USDC, USDT, DAI) to their card.
- Implemented a virtual keypad for amount input and a max button to quickly set the deposit amount.
- Integrated token selection and balance display, auto-selecting the first available stablecoin.
- Added success and error handling with toast notifications for deposit transactions.
- Updated `CardDetails` to include navigation to the new deposit screen and added a modal for displaying card images.

Add DepositToCard component for stablecoin deposits

---

app/(protected)/(tabs)/send.tsx
app/(protected)/(tabs)/swap.tsx
app/register.tsx
components/BankTransfer/payment/PaymentMethodList.tsx
components/ConnectedWalletDropdown.tsx
components/Dashboard/DashboardHeaderButtons.tsx
components/DepositOption/DepositOptions.web.tsx
components/DepositToVault/DepositToVaultForm.tsx
components/Navbar/index.tsx
components/Savings/ExtraYield.tsx
components/SendModal/SendModal.tsx
components/SendModal/index.tsx
components/Stake/StakeModal.tsx
components/Swap/SwapButton.tsx
components/Tooltip.tsx
components/Withdraw/WithdrawModal.tsx
components/Withdraw/index.tsx
constants/tracking-events.ts
hooks/useApprove.ts
hooks/useBridgeToMainnet.ts
hooks/useCancelOnchainWithdraw.ts
hooks/useDeposit.ts
hooks/useDepositFromEOA.ts
hooks/useSend.ts
hooks/useUser.ts
hooks/useWithdraw.ts

- Added tracking for user interactions in SendPage, SwapPage, and ConnectedWalletDropdown.
- Enhanced analytics in Deposit, Withdraw, and Stake modals to capture transaction statuses.
- Integrated tracking for deposit and withdrawal processes, including errors and user actions.
- Updated TooltipPopover to track tooltip openings with context.
- Refactored hooks to include user data in tracking events for better analytics insights.

Implement Firebase tracking across various components and hooks

---

hooks/useUser.ts

- Added reauthentication logic for web users to obtain a new session cookie and bind it to the selected user.
- Implemented error handling to revert to the previous user if reauthentication fails.
- Updated dependencies in the `handleSelectUser` function to include `user` and `unselectUser` in the dependency array.

Enhance user selection with web reauthentication

---

components/BankTransfer/BankTransferModalContent.tsx

- Added a new row for displaying the Deposit message.
- Updated the Beneficiary name row to include a divider for better visual separation.

Enhance BankTransferPreviewModal by adding Deposit message row and ensuring Beneficiary name has a divider

---

app/(protected)/(tabs)/savings.tsx
components/Dashboard/DashboardTitle.tsx
components/Navbar/NavbarMobile.tsx
components/ui/dialog.tsx
global.css

- Adjusted mobile positioning of the Intercom launcher in global.css.
- Modified spacing in the Savings component for better layout.
- Updated DashboardTitle link to direct to a more specific documentation page.
- Added Solid logo to the NavbarMobile component for branding.
- Improved dialog component styles for better visual consistency.

Enhance UI components and styles

---

hooks/useUser.ts

- Simplified the user signup function call by consolidating parameters into a single line.
- Enhanced logout behavior to redirect users to the onboarding screen on native platforms and the welcome screen on web platforms.

Refactor user signup and update logout routing logic

---

components/Card/AddToWalletModal.tsx
components/Card/CardDepositExternalForm.tsx
components/Card/CardDepositInternalForm.tsx

- Removed unused `CARD_DEPOSIT_MODAL` constant and its references in `CardDepositExternalForm` and `CardDepositInternalForm`.
- Simplified state management by removing `setModal` calls in both deposit forms.
- Updated text in `AddToWalletModal` to use HTML entities for quotes for better rendering.

Fix lint errors

---

components/Card/CardDepositExternalForm.tsx

- Added functionality to switch to the Arbitrum network before processing deposits.
- Integrated user feedback with Toast notifications for network switching and transaction processing.
- Implemented error handling for failed network switches to guide users in manual switching.
- Updated imports to include useSwitchActiveWalletChain for managing wallet chain changes.

Enhance CardDepositExternalForm with Arbitrum network switch

---

components/Card/CardDepositInternalForm.tsx
components/Card/DepositToCardModal.tsx
constants/tracking-events.ts
hooks/useBridgeToCard.ts
lib/api.ts
lib/types.ts

- Changed link in CardDepositInternalForm to point to LayerZeroScan instead of Fusescan.
- Updated text from "Bridge amount" to "Deposit amount" for better user understanding.
- Increased minimum height of DepositToCardModal for improved layout.
- Removed unnecessary console logs in useBridgeToCard hook to clean up the code.
- Updated function selector in useBridgeToCard for accuracy in transaction handling.

Bridge-funds-into-arbitrum-to-deposit-into-card
